const glossary = {
    "Routeur": "Périphérique de couche 3 (Réseau) qui achemine les paquets entre différents réseaux en utilisant des adresses IP.",
    "Commutateur": "Ou 'Switch'. Périphérique de couche 2 (Liaison de données) qui connecte des appareils sur un même réseau local (LAN) et utilise des adresses MAC.",
    "Switch": "Voir 'Commutateur'. Connecte des périphériques sur un LAN.",
    "Adresse IP": "Identifiant logique unique attribué à chaque interface sur un réseau utilisant le protocole Internet (IP).",
    "Adresse MAC": "Identifiant physique unique attribué à une interface réseau, utilisé pour la communication sur le même segment réseau.",
    "OSI": "Modèle de référence à 7 couches pour les communications réseau (Physique, Liaison, Réseau, Transport, Session, Présentation, Application).",
    "TCP": "Transmission Control Protocol. Protocole de transport fiable, orienté connexion, qui garantit la livraison des données.",
    "UDP": "User Datagram Protocol. Protocole de transport simple, sans connexion, rapide mais sans garantie de livraison (utilisé pour la voix, vidéo).",
    "DHCP": "Dynamic Host Configuration Protocol. Protocole qui attribue automatiquement des adresses IP et des paramètres réseau aux clients.",
    "DNS": "Domain Name System. Système qui traduit les noms de domaine (ex: www.cisco.com) en adresses IP.",
    "SSH": "Secure Shell. Protocole sécurisé pour accéder à distance à la ligne de commande d'un périphérique (chiffré).",
    "Telnet": "Protocole d'accès à distance non sécurisé (texte clair).",
    "Ping": "Utilitaire utilisant ICMP pour tester la connectivité avec un autre hôte IP.",
    "Tracert": "Ou 'traceroute'. Utilitaire qui affiche le chemin (les routeurs) emprunté par un paquet jusqu'à sa destination.",
    "ARP": "Address Resolution Protocol. Protocole utilisé pour trouver l'adresse MAC associée à une adresse IP connue.",
    "LAN": "Local Area Network. Réseau local, couvrant une petite zone géographique (maison, bureau).",
    "WAN": "Wide Area Network. Réseau étendu, couvrant une grande zone géographique (internet).",
    "VLAN": "Virtual LAN. Réseau local virtuel permettant de segmenter un commutateur en plusieurs réseaux logiques.",
    "Masque de sous-réseau": "Sépare l'adresse IP en partie réseau et partie hôte.",
    "Passerelle par défaut": "L'adresse IP du routeur utilisée par un hôte pour communiquer avec des appareils sur d'autres réseaux.",
    "Firewall": "Pare-feu. Système de sécurité qui surveille et contrôle le trafic réseau entrant et sortant.",
    "Serveur": "Ordinateur ou système qui fournit des ressources, des données, des services ou des programmes à d'autres ordinateurs (clients).",
    "Client": "Ordinateur ou logiciel qui demande des services à un serveur.",
    "HTTP": "HyperText Transfer Protocol. Protocole utilisé pour transmettre des pages web (port 80).",
    "HTTPS": "Version sécurisée de HTTP (port 443).",
    "FTP": "File Transfer Protocol. Protocole de transfert de fichiers.",
    "SMTP": "Simple Mail Transfer Protocol. Protocole d'envoi de courriels.",
    "POP3": "Post Office Protocol v3. Protocole de réception de courriels (télécharge et supprime du serveur généralement).",
    "IMAP": "Internet Message Access Protocol. Protocole de réception de courriels (synchronise avec le serveur).",
    "Unicast": "Communication d'un expéditeur vers un seul destinataire.",
    "Broadcast": "Diffusion. Communication d'un expéditeur vers tous les destinataires du réseau.",
    "Multicast": "Communication d'un expéditeur vers un groupe spécifique de destinataires.",
    "Console": "Port physique sur un périphérique Cisco pour l'administration locale directe.",
    "VTY": "Lignes de terminal virtuel utilisées pour l'accès distant (Telnet/SSH).",
    "Interface": "Port physique ou virtuel sur un périphérique réseau.",
    "Protocole": "Ensemble de règles régissant l'échange de données.",
    "Encapsulation": "Processus d'ajout d'en-têtes et de pieds de page aux données à chaque couche du modèle OSI.",
    "Trame": "Unité de données de protocole (PDU) de la couche 2 (Liaison de données).",
    "Paquet": "Unité de données de protocole (PDU) de la couche 3 (Réseau).",
    "Segment": "Unité de données de protocole (PDU) de la couche 4 (Transport).",
    "Full-duplex": "Communication bidirectionnelle simultanée.",
    "Half-duplex": "Communication bidirectionnelle mais alternée (un seul sens à la fois).",
    "Ethernet": "Technologie de réseau local la plus courante.",
    "Wi-Fi": "Technologie de réseau local sans fil (WLAN).",
    "IPv4": "Version 4 du protocole IP, utilisant des adresses de 32 bits.",
    "IPv6": "Version 6 du protocole IP, utilisant des adresses de 128 bits.",
    "Metric": "Valeur utilisée par les protocoles de routage pour déterminer le meilleur chemin.",
    "Hop": "Saut. Le passage d'un paquet par un routeur intermédiaire.",
    "TTL": "Time To Live. Champ dans l'en-tête IP qui décrémente à chaque saut pour éviter les boucles infinies.",
    "EMI": "Interférence électromagnétique.",
    "Crosstalk": "Diaphonie. Perturbation du signal causée par des fils adjacents.",
    "Hub": "Concentrateur. Périphérique de couche 1 obsolète qui diffuse les données à tous les ports.",
    "NIC": "Network Interface Card. Carte réseau.",
    "Topologie": "Disposition physique ou logique des périphériques réseau.",
    "MFA": "Authentification multifacteur. Sécurité accrue nécessitant plusieurs méthodes de vérification.",
    "Malware": "Logiciel malveillant (virus, ver, trojan, etc.).",
    "Virus": "Malware nécessitant une action humaine pour se propager.",
    "Ver": "Worm. Malware capable de se propager seul à travers le réseau.",
    "Trojan": "Cheval de Troie. Logiciel d'apparence légitime cachant une fonction malveillante.",
    "Phishing": "Hameçonnage. Tentative d'escroquerie pour obtenir des informations confidentielles.",
    "DoS": "Denial of Service. Attaque visant à rendre un service indisponible.",
    "DDoS": "Distributed DoS. Attaque DoS provenant de multiples sources.",
    "VPN": "Virtual Private Network. Réseau privé virtuel, tunnel sécurisé sur un réseau public.",
    "WPA": "Wi-Fi Protected Access. Protocole de sécurité pour les réseaux sans fil.",
    "SSID": "Service Set Identifier. Nom du réseau Wi-Fi.",
    "SVI": "Switch Virtual Interface. Interface virtuelle sur un commutateur pour le routage ou la gestion.",
    "NVRAM": "Mémoire vive non volatile. Stocke le fichier de configuration de démarrage (startup-config).",
    "Flash": "Mémoire stockant l'image du système d'exploitation IOS.",
    "RAM": "Mémoire vive. Stocke la configuration en cours (running-config).",
    "ROM": "Mémoire morte. Contient le programme de démarrage (bootstrap).",
    "IOS": "Internetwork Operating System. Système d'exploitation des périphériques Cisco.",
    "CLI": "Command Line Interface. Interface en ligne de commande.",
    "GUI": "Graphical User Interface. Interface graphique.",
    "Promiscuous mode": "Mode où une carte réseau capture tout le trafic, pas seulement celui qui lui est destiné."
};
